---
- hosts: all 
  become: true 
  tasks: 
  -  name: Deploy a user a called mercy 
     user: 
      name: mercy 
      create_home: true 
      shell: /bin/bash 
      comment: "mercy is our devops engineer" 
      expires: -1 
     
...